before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: xkxlimjazZnzPMALs7oudY6Xnf6tmQq/5EXdtZOMbNHP0Dykh/cGtysUdHXdwdtcvde7SV/1VV9ATUmalV875RfrsLbWsTngo8bj11b/7InGyMiPq7LaTpiw1+njr7aUdNmp6qSOI81laY/KAzPe7BGvHHATHYpfSL6qs7XM8QH/aZsDv1oKZgkOZM+mQCOlOYya8jhQCtqOWN/VhP1JqIS0suhJ2E1JThIU2RRZkiIjE9jYX/Mq0RcVw6to/gjA+DDFeYD/323Ysn70s+o7gKbmfQvfNNSnNAWjdqaFi0FsbnbDy52KZCglrxhK8JJLzU5HlwkGfOH4/58jh2cuzKa0f5L2N6Y4ij7k7caoUzxapqZHE+5KPthF8xofQgQMvYXXyizRNrtng3ZLR59UZKWgx0YMfjI6ecBxOqTW885OvVxuPVz8EXtcGGvVpwW9fbHa0lnFHOtqz5t9/XejUUNT+MU/7q1o3WLGuFel1qHA1MA+xmN/6x57A5mnioSuvfMWA9ImrtKzL78Z6/a6HGlQmZzWw1MsS43XUkYI7onTt42sX3DSu+MhSmozKqFubmv0fZ650BkfrcOF9XI4BBDg70tTrIcrZ3HCD66vLUtfpLBA0Rc2z7F4mt5ffx0zRV40e+88r/WF3sdCtzfpqxxTbrm95PMBpqwAkjSijew= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
